FROM postgres:9.6

COPY ./docker-entrypoint-initdb.d/hive-schema-2.3.0.postgres.sql /docker-entrypoint-initdb.d/hive-schema-2.3.0.postgres.sql
COPY ./docker-entrypoint-initdb.d/hive-txn-schema-2.3.0.postgres.sql /docker-entrypoint-initdb.d/hive-txn-schema-2.3.0.postgres.sql

ADD ./docker-entrypoint-initdb.d/init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
RUN chmod 755 /docker-entrypoint-initdb.d/init-user-db.sh

EXPOSE 5432
